### ISSUE TITLE
Bug? ProgramAddress is wrong

### ISSUE THREAD

**Issue by neverything** [tighten/solana-php-sdk#12]
This morning I ran into an issue with `PublicKey::findProgramAddress()`. When I try to get the proper address for https://solscan.io/token/ApqMgGY9sbseui4QKoerDui61PbUADD1CfZZGWC6eWF5 

- Trying to [findProgramAddress for ApqMgGY9sbseui4QKoerDui61PbUADD1CfZZGWC6eWF5](https://solscan.io/token/ApqMgGY9sbseui4QKoerDui61PbUADD1CfZZGWC6eWF5) it returns the wrong address
- Address returned: `9ajTce3dAtFaG6jJrNPq9vBVW4mwWDgmPqbZybvZYrzj`, nonce `255`
- Should be: `5zhP1LiHVw6rgZRRWqzV6Vh97RBJM7kZ9i3HjtynKu6S`, nonce `254`
- Tested on https://www.vicyyn.com/#/nft?ApqMgGY9sbseui4QKoerDui61PbUADD1CfZZGWC6eWF5

In order to quickly fix it in my job, I did the following:

```php
protected function maybeGetMetaData() : array
    {
        while ($this->currentNonce != 0) {
            $client = new SolanaRpcClient(SolanaRpcClient::MAINNET_ENDPOINT);
            $account = $client->call('getAccountInfo', [$this->programAddress, ["encoding" => "jsonParsed"]]);

            if (! $this->hasEncodedMetaData($account)) {
                $this->currentNonce--;
                $this->canGetProgramAddress();
                sleep(1);
                continue;
            }
            return $account;
        }
        return [];
    }
```

So basically as long as the `getAccountInfo` call returns an array that is missing the Borsh data `$this->canGetProgramAddress` is calling a custom version of `findProgramAddress` that accepts the nonce as a third parameter.

```php
/**
     * @param  array  $seeds
     * @param  PublicKey  $programId
     * @param  int  $nonce
     * @return array 2 elements, [0] = PublicKey, [1] = integer
     * @throws BaseSolanaPhpSdkException
     */
    static function findProgramAddress(array $seeds, PublicKey $programId, int $nonce = 255): array
    {
        while ($nonce != 0) {
            try {
                $copyOfSeedsWithNonce = $seeds;
                array_push($copyOfSeedsWithNonce, [$nonce]);
                $address = PublicKey::createProgramAddress($copyOfSeedsWithNonce, $programId);
            } catch (\Exception $exception) {
                $nonce--;
                continue;
            }
            return [$address, $nonce];
        }

        throw new BaseSolanaPhpSdkException('Unable to find a viable program address nonce.');
    }
```

Not very elegant and I have to rate limit the calls to the enpoints 😅, but it does the trick for me.

**Comment by exzachlyvv** [comment]
What $seeds and $programId are you using?

**Comment by mattstauffer** [comment]
@exzachlyvv D you need me to jump in here to try to be helpful? Even as ignorant as I am? 😆  or can you handle this some time?

**Comment by neverything** [comment]
No rush at all my workaround is working for now 😎.

Btw are you guys at Solana Breakpoint in Lisbon this week? Would love to say thanks for the work you have been putting into this.

**Comment by exzachlyvv** [comment]
Hey guys! I've gotten pulled away from Solana development for now so not sure I'll have too much time helping out with this project in the short term. Happy to step in if you get in a pinch 😄 

I won't be at Solana Breakpoint 😢  but have fun 🕺

**Comment by neverything** [comment]
Hey @exzachlyvv ohh sad to hear and thanks for offering your help, I guess I'll need it eventually 😅. @mattstauffer should I try and prepare a seperate version for borsh-php based on the amazing work @exzachlyvv did so far? Still learning how to properly use it, but might have some time this weekend after breakpoint.

Btw. amazing event and good vibes only.

**Comment by mattstauffer** [comment]
@neverything Sorry I missed this question! I'd love that, if you're up for it!

**Comment by danieljao** [comment]
hi @neverything can i ask question?  where did you add your workaround? can you please share, i believe i need your workaround too, i hope you can share

**Comment by danieljao** [comment]
hi @mattstauffer does the `Metadata::fromBuffer` return creator? im getting array but no value, is that correct? just confirming

**Comment by neverything** [comment]
@danieljao sorry just saw your question. The workaround is in my job class to get the NFT metadata.

**Comment by danieljao** [comment]
> @danieljao sorry just saw your question. The workaround is in my job class to get the NFT metadata.

Hi @neverything just wondering if the Job class you have is in the repo? just wondering if i can check it out, thank you
