### ISSUE TITLE
How to deal with rate limits of JSON RPC?

### ISSUE THREAD

**Issue by faridmovsumov** [tighten/solana-php-sdk#23]
Hello,

I found documentation regarding limitations but couldn't find any information regarding proper rate limit controls.

![image](https://user-images.githubusercontent.com/1541412/150392028-10350c7c-c93c-4611-93b2-29f601de5b90.png)

https://docs.solana.com/cluster/rpc-endpoints#mainnet-beta

Normally I would expect some header to tell me regarding my quota information to be able to sleep my code for some time but I was able to only get HTTP 429 after I got an error and then retry failed requests which is not the most efficient approach. I am wondering if you figured out already some solution for this problem.

**Comment by faridmovsumov** [comment]
I think the answer is to use private RPC services recommended on the Solana website. https://solana.com/rpc

![image](https://user-images.githubusercontent.com/1541412/150602553-429fc9ab-29f5-4a4b-98e0-73b471a86057.png)

**Comment by neverything** [comment]
Hey @faridmovsumov which RPC service did you end up using? I'm currently handling the rate limits with a cache key that is set and releases the jobs back to the queue after the time is up.

**Comment by neverything** [comment]
Hehe same @faridmovsumov, ran into more rate limits and thinking about giving QuickNode a try.

**Comment by faridmovsumov** [comment]
Seems like for production-ready applications some solid RPC server is a must.
